# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: false
default_language_version:
  python: python3
exclude: |
  (?x)(
      \.(html|js|css)$
  )
repos:
  - repo: 'https://github.com/Lucas-C/pre-commit-hooks-safety'
    rev: v1.2.2
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml
        additional_dependencies: ['poetry']
  - repo: 'https://github.com/PyCQA/bandit'
    rev: 1.7.1
    hooks:
      - id: bandit
        additional_dependencies: ['toml']
        # not support auto read config from `pyproject.toml` for now
        args: ['-c', "pyproject.toml"]
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v2.29.1
    hooks:
      - id: pyupgrade
  - repo: 'https://github.com/PyCQA/pydocstyle'
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies: ['toml']
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.10.1
    hooks:
      - id: isort
        types_or: [python, cython, pyi]
  - repo: 'https://github.com/PyCQA/flake8'
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: 'https://github.com/pre-commit/pygrep-hooks'
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--django]
        exclude: tests/fixtures/.*\.json|tests/fixture\.py|tests/base\.py
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: check-executables-have-shebangs
      - id: check-added-large-files
        args: [--enforce-all]
      - id: detect-private-key
      - id: check-merge-conflict
  - repo: 'https://github.com/psf/black'
    rev: 21.11b1
    hooks:
      - id: black
